### ISSUE TITLE
Use the library without audio/video streaming features.

### ISSUE THREAD

**Issue by iSLC** [RealTimeChris/DiscordCoreAPI#30]
Can the library be used without the audio/video streaming functionality?

I.e. Disable it at compile time and not having to link with necessary dependencies: FFMPEG or Opus.

Ideally this should be possible, because it removes complexity that may not be needed by whoever used the library.

**Comment by RealTimeChris** [comment]
Alright thanks for letting me know!

**Comment by ben-forster** [comment]
Like plugins?

**Comment by iSLC** [comment]
Upon further review. It is really hard to justify this library. It uses AVX512 instructions with no fallback to older instruction sets or non SIMD implementations. Meaning you must use it on quite recent Intel CPUs (2016 and up) and not all of them. AMD just barely implemented this in Zen4 architecture this year. And the funny part is that Intel is starting to remove AVX512 from some of its CPUs. So you're already quite limited on the amount of hardware that you can run this.

While this library might be fast (_as advertised_) and lightweight. I'd suggest using D++ instead. The downsides of d++ is the very long time it takes to compile. If you're thinking of using GH actions to test your builds. It could take 3+ hours to build it every time (_at least_). Locally it may be less. But still a significant amount of time.

Sleepy Discord is getting outdated. There are a couple C libraries that are maintained but they have an intricate build system where they generate C source files from some specialized template language and then build from that.

Suffice to say that Discord is not for c/c++ (_yet_). At least not without compromise. So I gave up on even trying.

**Comment by RealTimeChris** [comment]
It doesn't use AVX512 it uses AVX2 instructions which only require a CPU from roughly 2013 or newer.

**Comment by RealTimeChris** [comment]
> Upon further review. It is really hard to justify this library. It uses AVX512 instructions with no fallback to older instruction sets or non SIMD implementations. Meaning you must use it on quite recent Intel CPUs (2016 and up) and not all of them. AMD just barely implemented this in Zen4 architecture this year. And the funny part is that Intel is starting to remove AVX512 from some of its CPUs. So you're already quite limited on the amount of hardware that you can run this.
> 
> While this library might be fast (_as advertised_) and lightweight. I'd suggest using D++ instead. The downsides of d++ is the very long time it takes to compile. If you're thinking of using GH actions to test your builds. It could take 3+ hours to build it every time (_at least_). Locally it may be less. But still a significant amount of time.
> 
> Sleepy Discord is getting outdated. There are a couple C libraries that are maintained but they have an intricate build system where they generate C source files from some specialized template language and then build from that.
> 
> Suffice to say that Discord is not for c/c++ (_yet_). At least not without compromise. So I gave up on even trying.



> Upon further review. It is really hard to justify this library. It uses AVX512 instructions with no fallback to older instruction sets or non SIMD implementations. Meaning you must use it on quite recent Intel CPUs (2016 and up) and not all of them. AMD just barely implemented this in Zen4 architecture this year. And the funny part is that Intel is starting to remove AVX512 from some of its CPUs. So you're already quite limited on the amount of hardware that you can run this.
> 
> While this library might be fast (_as advertised_) and lightweight. I'd suggest using D++ instead. The downsides of d++ is the very long time it takes to compile. If you're thinking of using GH actions to test your builds. It could take 3+ hours to build it every time (_at least_). Locally it may be less. But still a significant amount of time.
> 
> Sleepy Discord is getting outdated. There are a couple C libraries that are maintained but they have an intricate build system where they generate C source files from some specialized template language and then build from that.
> 
> Suffice to say that Discord is not for c/c++ (_yet_). At least not without compromise. So I gave up on even trying.

**Comment by RealTimeChris** [comment]
> Upon further review. It is really hard to justify this library. It uses AVX512 instructions with no fallback to older instruction sets or non SIMD implementations. Meaning you must use it on quite recent Intel CPUs (2016 and up) and not all of them. AMD just barely implemented this in Zen4 architecture this year. And the funny part is that Intel is starting to remove AVX512 from some of its CPUs. So you're already quite limited on the amount of hardware that you can run this.
> 
> While this library might be fast (_as advertised_) and lightweight. I'd suggest using D++ instead. The downsides of d++ is the very long time it takes to compile. If you're thinking of using GH actions to test your builds. It could take 3+ hours to build it every time (_at least_). Locally it may be less. But still a significant amount of time.
> 
> Sleepy Discord is getting outdated. There are a couple C libraries that are maintained but they have an intricate build system where they generate C source files from some specialized template language and then build from that.
> 
> Suffice to say that Discord is not for c/c++ (_yet_). At least not without compromise. So I gave up on even trying.

It doesn't use AVX512 it uses AVX2 instructions which only require a CPU from roughly 2013 or newer.

**Comment by iSLC** [comment]
> It doesn't use AVX512 it uses AVX2 instructions which only require a CPU from roughly 2013 or newer.

https://github.com/RealTimeChris/DiscordCoreAPI/blob/1c1d933375e5a28af47580ed90c04a5f70137d4a/Library/CMakeLists.txt#LL115C3-L115C30

```cmake
target_compile_options(
	#...
	"$<$<CXX_COMPILER_ID:GNU>:-mavx512f>"
	"$<$<CXX_COMPILER_ID:GNU>:-march=native>"
)
```

It wouldn't compile without AVX512 for me.

**Comment by RealTimeChris** [comment]
Did you try compiling it with AVX2 enabled? Or just -march=native? What OS/CPU are you running on? Because that doesn't make any sense - try to find a single AVX512 instruction in the code - you can't because there isn't any. As for that flag - that is a mistake for it being in there, my apologies for that. It's not in the official released version.
https://github.com/RealTimeChris/DiscordCoreAPI/blob/Current-Vcpkg/Library/CMakeLists.txt#L112-L115
