### ISSUE TITLE
Incorrect file naming

### ISSUE THREAD

**Issue by ghost** [RealTimeChris/DiscordCoreAPI#4]
`MessageEntites.hpp` tries to include `JSONIFier.hpp` which fails, as the actual file is named `JSONIfier.hpp`. Renaming it to what `MessageEntities.hpp` needs it to be creates errors from other files, so I'm assuming that `MessageEntities.hpp` just has a typo.

**Comment by ghost** [comment]
![image](https://user-images.githubusercontent.com/87716499/151640789-19f1fa73-11dd-4066-a105-91e871048316.png)

**Comment by RealTimeChris** [comment]
Ooof! Thanks for letting me know! It should be good now!
